stages:
  - build
  - test

image: docker:19.03.0

services:
  - docker:19.03.0-dind

build image:
  stage: build
  script:
    - docker build -t py-mkdocs .
  only:
    refs:
      - develop
      - master
  except:
    changes:
      - "README.md"

run container:
  stage: test
  script:
    - ./mkdockerize.sh
  only:
    refs:
      - develop
      - master
  except:
    changes:
      - "README.md"
