stages:
  - test
  - build
  - deploy

image: docker:19.03.12

services:
  - docker:19.03.12-dind

Sonarqube-check:
  stage: test
  image: python:2.7-slim
  script:
    - echo 'scanning code quality'
  only:
    refs:
      - develop
  except:
    changes:
      - "README.md"

syntax-check:
  stage: test
  image: python:2.7-slim
  script:
    - pip install pylint
    - pylint *.py --confidence=INFERENCE
  only:
    refs:
      - develop
  except:
    changes:
      - "README.md"

build image:
  stage: build
  script:
    #- docker build -t py-mkdocs .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - docker build -t registry.gitlab.com/lok.bruce/mkdocs .
    - docker push registry.gitlab.com/lok.bruce/mkdocs:latest
  only:
    refs:
      - develop
  except:
    changes:
      - "README.md"

run container:
  stage: deploy
  script:
    - ./mkdockerize.sh
    - sleep 5
    - docker exec -i my-mkdocs python http_test.py
  only:
    refs:
      - master
  except:
    changes:
      - "README.md"
