stages:
  - build
  - test

image: docker:stable

build image:
  stage: build
  script:
    - docker build -t py-mkdocs .
  only:
    refs:
      - develop
      - master

run container:
  stage: test
  script:
    - ./mkdockerize.sh
  only:
    refs:
      - develop
      - master
