site_name: Query Mac API
site_url: https://gitlab.com/lok.bruce/query-mac-api
site_description: A simple API in Python to query manufacturer of a Mac address from https://macaddress.io.
site_author: lok.bruce@gmail.com
nav:
    - Home: index.md
    - About: about.md
dev_addr: '0.0.0.0:8000'
